export const FETCH_CART_ITEM_REQUEST = "FETCH_CART_ITEM_REQUEST";
export const FETCH_CART_ITEM_SUCCESS = "FETCH_CART_ITEM_SUCCESS";
export const FETCH_CART_ITEM_FAILURE = "FETCH_CART_ITEM_FAILURE";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const UPDATE_CART_ITEM_QTY_SUCCESS = "UPDATE_CART_ITEM_QTY_SUCCESS";

export const DELETE_ITEM_IN_CART_SUCCESS = "DELETE_ITEM_IN_CART_SUCCESS";

export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
