export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";

export const CLEAR_CURRENT_ORDER_SUCCESS = "CLEAR_CURRENT_ORDER_SUCCESS";

export const FETCH_ORDER_BY_USER_ID_SUCCESS = "FETCH_ORDER_BY_USER_ID_SUCCESS";

export const FETCH_ALL_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";

export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
