export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";

export const SAVE_SHIPPING_ADDRESS_SUCCESS = "SAVE_SHIPPING_ADDRESS_SUCCESS";

export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";

export const CHECKED_USER_LOGGEDIN_OR_NOT_SUCCESS =
  "CHECKED_USER_LOGGEDIN_OR_NOT_SUCCESS";
export const CHECKED_USER_LOGGEDIN_OR_NOT_FAILURE =
  "CHECKED_USER_LOGGEDIN_OR_NOT_FAILURE";

export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";

export const EDIT_USER_ROLE_SUCCESS = "EDIT_USER_ROLE_SUCCESS";
